# Generated by Django 3.0.7 on 2020-08-23 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motels', '0008_auto_20200822_2235'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Mệnh giá')),
            ],
            options={
                'verbose_name': 'Mệnh giá',
                'verbose_name_plural': 'Mệnh giá',
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Nhà mạng')),
            ],
            options={
                'verbose_name': 'Nhà mạng',
                'verbose_name_plural': 'Nhà mạng',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Giá trị')),
                ('discount7', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount30', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Các gói Vip',
                'verbose_name_plural': 'Các gói Vip',
            },
        ),
        migrations.CreateModel(
            name='PostedAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đẩy')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Số ngày chạy')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='motels.Post', verbose_name='Bài đăng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='Mệnh giá')),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_vip', to='finance.Vip', verbose_name='Gói Vip')),
            ],
            options={
                'verbose_name': 'Lịch sử đẩy tin',
                'verbose_name_plural': 'Lịch sử đẩy tin',
            },
        ),
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=50, verbose_name='Ghi chú')),
                ('request_id', models.IntegerField(verbose_name='Request id')),
                ('value', models.IntegerField(verbose_name='Giá trị thẻ')),
                ('amount', models.IntegerField(verbose_name='Doanh thu')),
                ('code', models.CharField(max_length=50, verbose_name='Mã thẻ')),
                ('serial', models.CharField(max_length=50, verbose_name='Số seri')),
                ('trans_id', models.CharField(max_length=100)),
                ('callback_sign', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nạp')),
                ('declared_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='finance.CardAmount', verbose_name='Tiền nạp')),
                ('telco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='finance.CardType', verbose_name='Nhà mạng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Mệnh giá')),
            ],
            options={
                'verbose_name': 'Lịch sử nạp',
                'verbose_name_plural': 'Lịch sử nạp',
            },
        ),
    ]
