# Generated by Django 3.0.7 on 2020-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200823_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
