# Generated by Django 3.0.7 on 2020-08-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200823_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='callback_sign',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
