# Generated by Django 3.0.7 on 2020-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200823_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='request_id',
            field=models.CharField(max_length=69, verbose_name='Request id'),
        ),
    ]
