# Generated by Django 3.0.7 on 2020-08-25 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_auto_20200824_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Doanh thu thực tế'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='request_id',
            field=models.CharField(max_length=69, verbose_name='Mã giao dịch'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Người nạp'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='value',
            field=models.IntegerField(null=True, verbose_name='Giá trị thẻ'),
        ),
    ]
