# Generated by Django 3.0.7 on 2020-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20200825_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
