# Generated by Django 3.0.7 on 2020-08-25 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200825_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số ngày')),
                ('is_active', models.BooleanField(verbose_name='Hiệu lực')),
            ],
            options={
                'verbose_name': 'Các gói giảm giá',
                'verbose_name_plural': 'Các gói giảm giá',
            },
        ),
        migrations.RemoveField(
            model_name='postedads',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='discount30',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='discount7',
        ),
        migrations.AddField(
            model_name='vip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian tạo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postedads',
            name='vip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Vip', verbose_name='Gói vip'),
        ),
        migrations.AddField(
            model_name='postedads',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.Discount', verbose_name='Mã giảm giá'),
        ),
    ]
