# Generated by Django 3.0.7 on 2020-08-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_auto_20200825_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Thu về'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='declared_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='finance.CardAmount', verbose_name='Tiền nạp'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='telco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='finance.CardType', verbose_name='Nhà mạng'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Người nạp'),
        ),
        migrations.AlterField(
            model_name='postedads',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Discount', verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='postedads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='Mệnh giá'),
        ),
        migrations.AlterField(
            model_name='postedads',
            name='vip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Vip', verbose_name='Gói vip'),
        ),
    ]
