# Generated by Django 3.0.7 on 2020-08-28 06:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motels', '0016_auto_20200828_0601'),
        ('finance', '0009_auto_20200825_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardamount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cardhistory',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name': 'Telecom', 'verbose_name_plural': 'Telecom'},
        ),
        migrations.RemoveField(
            model_name='postedads',
            name='user',
        ),
        migrations.AddField(
            model_name='postedads',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='motels.Post', verbose_name='Bài đăng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardamount',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Return Value'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='declared_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='finance.CardAmount', verbose_name='Declared value '),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='message',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='request_id',
            field=models.CharField(max_length=69, verbose_name='Request id'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='serial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='telco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='finance.CardType', verbose_name='Telecom'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='value',
            field=models.IntegerField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Telecom'),
        ),
    ]
