# Generated by Django 3.0.7 on 2020-08-28 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20200828_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postedads',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterField(
            model_name='vip',
            name='amount',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Giá trị'),
        ),
    ]
