# Generated by Django 3.0.7 on 2020-08-28 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20200828_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discount'},
        ),
        migrations.AlterField(
            model_name='vip',
            name='amount',
            field=models.IntegerField(help_text='<span style="position:absolute;left:205px; top:17px ">VND</span>', unique=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Amount/day'),
        ),
    ]
