# Generated by Django 3.0.7 on 2020-09-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20200828_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='postedads',
            name='discount',
        ),
        migrations.CreateModel(
            name='VipDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Hiệu lực')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Discount')),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Vip')),
            ],
        ),
        migrations.AddField(
            model_name='postedads',
            name='vip_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.VipDiscount', verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='vip',
            field=models.ManyToManyField(blank=True, related_name='vips', to='finance.Vip'),
        ),
    ]
