# Generated by Django 3.0.7 on 2020-09-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20200902_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Hiệu lực')),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='vip',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='vipdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Discount'),
        ),
        migrations.AddField(
            model_name='vipdiscount',
            name='vip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Vip'),
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.ManyToManyField(blank=True, related_name='vips', through='finance.VipDiscount', to='finance.Vip'),
        ),
        migrations.AddField(
            model_name='postedads',
            name='vip_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.VipDiscount', verbose_name='Mã giảm giá'),
        ),
    ]
