# Generated by Django 3.0.7 on 2020-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20200902_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedads',
            name='vip_discount',
        ),
        migrations.DeleteModel(
            name='VipDiscount',
        ),
    ]
