# Generated by Django 3.0.7 on 2020-09-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20200902_2240'),
    ]

    operations = [
    ]
