# Generated by Django 3.0.7 on 2020-09-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20200902_2242'),
    ]

    operations = [
    ]
