# Generated by Django 3.0.7 on 2020-09-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedads',
            name='vip_discount',
        ),
        migrations.DeleteModel(
            name='VipDiscount',
        ),
    ]
