# Generated by Django 3.0.7 on 2020-09-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20200902_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='Hiệu lực')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Discount')),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Vip')),
            ],
        ),
    ]
