# Generated by Django 3.0.7 on 2020-09-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_vipdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedads',
            name='vip_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.VipDiscount', verbose_name='Mã giảm giá'),
        ),
    ]
