# Generated by Django 3.0.7 on 2020-09-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_postedads_vip_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
    ]
