# Generated by Django 3.0.7 on 2020-07-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0003_auto_20200712_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_address', to='motels.Province', verbose_name='Address'),
        ),
    ]
