# Generated by Django 3.0.7 on 2020-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0005_auto_20200722_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
