# Generated by Django 3.0.7 on 2020-07-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0006_auto_20200723_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_rent',
        ),
    ]
