# Generated by Django 3.0.7 on 2020-08-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0006_auto_20200819_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Tin', 'verbose_name_plural': 'Tin'},
        ),
    ]
