# Generated by Django 3.0.7 on 2020-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0007_remove_room_max_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
