# Generated by Django 3.0.7 on 2020-08-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0007_auto_20200819_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularuserhistory',
            options={'verbose_name': 'Tin chờ duyệt', 'verbose_name_plural': 'Tin chờ duyệt'},
        ),
    ]
