# Generated by Django 3.0.7 on 2020-08-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0008_auto_20200822_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motels.Post'),
        ),
        migrations.AlterField(
            model_name='postfollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regularuserhistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='motels.PostStatus'),
        ),
        migrations.AlterField(
            model_name='regularuserhistory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='motels.Province', verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='motels.Post'),
        ),
    ]
