# Generated by Django 3.0.7 on 2020-07-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0008_room_max_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
    ]
