# Generated by Django 3.0.7 on 2020-07-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0009_remove_apartment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='max_area',
        ),
    ]
