# Generated by Django 3.0.7 on 2020-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0009_auto_20200825_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
