# Generated by Django 3.0.7 on 2020-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0010_remove_post_max_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddress',
            name='detailed_address',
            field=models.CharField(max_length=150),
        ),
    ]
