# Generated by Django 3.0.7 on 2020-07-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0011_auto_20200724_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackForHiding',
            new_name='AllFeedback',
        ),
        migrations.RemoveField(
            model_name='post',
            name='electricity_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='water_price',
        ),
    ]
