# Generated by Django 3.0.7 on 2020-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0011_auto_20200825_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='regularuserhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Tin của bạn đang chờ duyệt'), (2, 'Tin của bạn đã được duyệt thành công'), (3, 'Tin của bạn không được duyệt'), (4, 'Bạn đã hủy yêu cầu duyệt tin'), (5, 'Tin của bạn đã bị ẩn bởi admin'), (6, 'Bạn đã ẩn tin của mình'), (7, 'Tin đã bỏ ẩn')], verbose_name='Trạng thái'),
        ),
    ]
