# Generated by Django 3.0.7 on 2020-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0013_auto_20200827_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
