# Generated by Django 3.0.7 on 2020-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0014_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
