# Generated by Django 3.0.7 on 2020-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motels', '0015_auto_20200827_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Category: Apartment'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Category: House'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Category: Room'},
        ),
        migrations.AlterModelOptions(
            name='roommate',
            options={'verbose_name': 'Category: Roommate'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bedrooms',
            field=models.IntegerField(verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_toilets',
            field=models.IntegerField(verbose_name='Number of toilets'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_bedrooms',
            field=models.IntegerField(verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_toilets',
            field=models.IntegerField(verbose_name='Number of toilets'),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_floor',
            field=models.IntegerField(verbose_name='Total floor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.FloatField(help_text='<span style="position:absolute;left:205px; top:17px ">m2</span>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Tìm bạn ở ghép'), (1, 'Cho thuê phòng trọ'), (2, 'Cho thuê nhà nguyên căn'), (3, 'Cho thuê nguyên căn chung cư')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='deposit',
            field=models.IntegerField(blank=True, help_text='<span style="position:absolute;left:205px; top:17px ">VND</span>', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='furniture',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='other_contact_info',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Other contact info'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent',
            field=models.IntegerField(help_text='<span style="position:absolute;left:205px; top:17px ">VND</span>', verbose_name='Ren/month'),
        ),
        migrations.AlterField(
            model_name='post',
            name='renters_gender',
            field=models.IntegerField(choices=[(0, 'Chỉ nữ'), (1, 'Chỉ nam'), (2, 'Tất cả')], verbose_name='Looking for'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=110, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='regularuserhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Tin của bạn đang chờ duyệt'), (2, 'Tin của bạn đã được duyệt thành công'), (3, 'Tin của bạn không được duyệt'), (4, 'Bạn đã hủy yêu cầu duyệt tin'), (5, 'Tin của bạn đã bị khóa'), (6, 'Bạn đã ẩn tin của mình'), (7, 'Tin đã bỏ ẩn')], verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_rent',
            field=models.IntegerField(blank=True, help_text='<span style="position:absolute;left:205px; top:17px ">VND</span>', null=True, verbose_name='Max rent'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, help_text='<span style="position:absolute;left:205px; top:17px ">room</span>', null=True, verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='roommate',
            name='number_of_roommate',
            field=models.IntegerField(help_text='<span style="position:absolute;left:205px; top:17px ">people</span>', verbose_name='Looking for'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Date join'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
    ]
